# Generated by Django 3.0.4 on 2020-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default='f16260894b264380bad056c75cb56546', editable=False, primary_key=True, serialize=False),
        ),
    ]
