# Generated by Django 3.0.4 on 2020-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_auto_20200331_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default='eee305e991c3420fb4ba674ba94947bb', editable=False, primary_key=True, serialize=False),
        ),
    ]
