# Generated by Django 3.0.5 on 2020-04-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_auto_20200405_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
