# Generated by Django 3.0.5 on 2020-04-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking_app', '0003_auto_20200401_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.AccountHolder'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default='5955d110f4fd4f24b5249c024e0e4654', editable=False, primary_key=True, serialize=False),
        ),
    ]
