# Generated by Django 3.0.5 on 2020-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0004_auto_20200401_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default='3e1326bef1414f568decf6dec4d8a923', editable=False, primary_key=True, serialize=False),
        ),
    ]
