# Generated by Django 3.0.5 on 2020-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0006_auto_20200401_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default='84b770ea31824665a71cb38613a1c579', editable=False, primary_key=True, serialize=False),
        ),
    ]
