# Generated by Django 3.0.5 on 2020-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0010_transaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.IntegerField(choices=[(1, 'Withdraw'), (2, 'Deposit')]),
        ),
    ]
