# Generated by Django 3.0.5 on 2020-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0011_auto_20200404_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], max_length=8),
        ),
    ]
