# Generated by Django 3.0.5 on 2020-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0012_auto_20200404_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
