# Generated by Django 3.0.5 on 2020-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0013_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
    ]
